/**
 * recipecate-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CookType = 'pressure-cooker' | 'stovetop' | 'oven' | 'slow-cooker' | 'grill';

export const CookType = {
    PressureCooker: 'pressure-cooker' as CookType,
    Stovetop: 'stovetop' as CookType,
    Oven: 'oven' as CookType,
    SlowCooker: 'slow-cooker' as CookType,
    Grill: 'grill' as CookType
};