/**
 * recipecate-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CookType } from './cookType';
import { Ingredient } from './ingredient';
import { RecipeCenterpieceType } from './recipeCenterpieceType';

export interface Recipe { 
    name: string;
    ingredients: Array<Ingredient>;
    instructions: string;
    cookType?: CookType;
    totalTimeMinutes?: number;
    recipeCenterpieceType?: RecipeCenterpieceType;
    id: string;
}