/**
 * recipecate-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type RecipeCenterpieceType = 'pork' | 'beef' | 'chicken' | 'vegetarian' | 'fish';

export const RecipeCenterpieceType = {
    Pork: 'pork' as RecipeCenterpieceType,
    Beef: 'beef' as RecipeCenterpieceType,
    Chicken: 'chicken' as RecipeCenterpieceType,
    Vegetarian: 'vegetarian' as RecipeCenterpieceType,
    Fish: 'fish' as RecipeCenterpieceType
};